<!DOCTYPE html>
<html>

<head>
    <script src="../node_modules/knockout/build/output/knockout-latest.debug.js"></script>
    <link rel="stylesheet" type="text/css" href="style.css"></link>
</head>

<body>
    <h2>ko hohum ko</h2>
    <p>First name:
        <input data-bind="value: firstName" />
    </p>
    <p>Last name:
        <input data-bind="value: lastName" />
    </p>
    <h2>Hello, <span data-bind="text: fullName"> </span>!</h2>
    
    <!-- ko data-bind="foreach: myItems" -->
        <div>Item <span data-bind="text: $data"></span></div>
    <!-- /ko -->
    
    <!-- I am a normal comment -->

    <ul data-bind="foreach: myItems">
        <li data-bind="text: $data"></li>
    </ul>
    
    <div><?php echo("I am PHP"); ?></div>

    <script>
        var ViewModel = function(first, last) {
            this.firstName = ko.observable(first);
            this.lastName = ko.observable(last);

            this.fullName = ko.computed(function() {
                // Knockout tracks dependencies automatically. It knows that fullName depends on firstName and lastName, because these get called when evaluating fullName.
                return this.firstName() + " " + this.lastName();
            }, this);
            this.myItems = ['A', 'B', 'C'];
        };

        ko.applyBindings(new ViewModel("Planet", "Earth")); // This makes Knockout get to work

    </script>
</body>

</html>